import { MovieRecommendation } from './types';

export const NETFLIX_INDIA_SEED_CATALOG: MovieRecommendation[] = [
  {
    id: "seed-1",
    title: "Laapataa Ladies",
    year: "2024",
    genre: ["Comedy", "Drama", "Social Change"],
    languages: ["Hindi"],
    duration: "122m",
    description: "In rural India, two young brides accidentally get swapped during a train ride, sparking a profound journey of self-discovery, empowerment, and hilarious community misunderstandings.",
    relevanceScore: 95,
    matchReason: "A heartwarming masterpiece perfect for a happy, wholesome Hindi viewing session.",
    netflixUrl: "https://www.netflix.com/search?q=Laapataa%20Ladies",
    isOriginal: false
  },
  {
    id: "seed-2",
    title: "Jaane Jaan",
    year: "2023",
    genre: ["Thriller", "Mystery", "Crime"],
    languages: ["Hindi", "English"],
    duration: "139m",
    description: "A single mother gets entangled in a murder investigation of her abusive husband, while her highly intellectual math teacher neighbor steps in to orchestrate a complex alibi.",
    relevanceScore: 92,
    matchReason: "A high-stakes suspenseful experience ideal for thriller lovers who want a deep, gripping mystery.",
    netflixUrl: "https://www.netflix.com/search?q=Jaane%20Jaan",
    isOriginal: true
  },
  {
    id: "seed-3",
    title: "Stranger Things",
    year: "2022",
    genre: ["Sci-Fi", "Mystery", "Adventure"],
    languages: ["English", "Hindi"],
    duration: "Series (45-75m)",
    description: "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl with telekinetic powers.",
    relevanceScore: 89,
    matchReason: "Great option to watch in parts or episodic segments, blending Nostalgia and sci-fi adrenaline.",
    netflixUrl: "https://www.netflix.com/search?q=Stranger%20Things",
    isOriginal: true
  },
  {
    id: "seed-4",
    title: "Amar Singh Chamkila",
    year: "2024",
    genre: ["Drama", "Music", "Biopic"],
    languages: ["Hindi"],
    duration: "145m",
    description: "Imtiaz Ali's chronicle of Punjab's wildest original rockstar, Amar Singh Chamkila, who rose from poverty to immense heights of fame through raw, controversial folk music before his tragic assassination.",
    relevanceScore: 93,
    matchReason: "Stirring blend of music and rich Indian rural subculture. Extremely energizing.",
    netflixUrl: "https://www.netflix.com/search?q=Amar%20Singh%20Chamkila",
    isOriginal: true
  },
  {
    id: "seed-5",
    title: "Drishyam",
    year: "2015",
    genre: ["Thriller", "Mystery", "Crime", "Drama"],
    languages: ["Hindi"],
    duration: "163m",
    description: "A cable-network owner uses knowledge acquired by binge-watching popular cinema to save his family from the brutal consequences of an accidental homicide.",
    relevanceScore: 94,
    matchReason: "Classic suspense thriller centering smart puzzle-planning, ideal for high focus sessions.",
    netflixUrl: "https://www.netflix.com/search?q=Drishyam",
    isOriginal: false
  },
  {
    id: "seed-6",
    title: "Sacred Games",
    year: "2019",
    genre: ["Crime", "Drama", "Action", "Mystery"],
    languages: ["Hindi", "English"],
    duration: "Series (45-55m)",
    description: "A link in their pasts leads an honest police officer to a fugitive gang boss whose apocalyptic warnings set off a countdown to save Mumbai from a devastating catastrophe.",
    relevanceScore: 90,
    matchReason: "Deeply cinematic series with premium production quality, perfect for watching in portions.",
    netflixUrl: "https://www.netflix.com/search?q=Sacred%20Games",
    isOriginal: true
  },
  {
    id: "seed-7",
    title: "Inception",
    year: "2010",
    genre: ["Sci-Fi", "Action", "Mind-bending"],
    languages: ["English", "Hindi"],
    duration: "148m",
    description: "A professional thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C-suite heir.",
    relevanceScore: 96,
    matchReason: "Mind-bending puzzle movie that requires intense investment. Perfect for intellectual curiosity.",
    netflixUrl: "https://www.netflix.com/search?q=Inception",
    isOriginal: false
  },
  {
    id: "seed-8",
    title: "The Railway Men",
    year: "2023",
    genre: ["Drama", "Historical", "Tragedy"],
    languages: ["Hindi", "English"],
    duration: "Mini-series (55m)",
    description: "After a leak at a union chemical plant poisons the air of Bhopal, heroic railway workers risk their lives to rescue hundreds of trapped citizens in the railway platform.",
    relevanceScore: 94,
    matchReason: "Tense, emotional historical drama featuring elite performances.",
    netflixUrl: "https://www.netflix.com/search?q=The%20Railway%20Men",
    isOriginal: true
  },
  {
    id: "seed-9",
    title: "Wednesday",
    year: "2022",
    genre: ["Mystery", "Fantasy", "Comedy"],
    languages: ["English", "Hindi"],
    duration: "Series (45-50m)",
    description: "Smart, sarcastic and a little dead inside, Wednesday Addams investigates a murder spree while making new friends — and foes — at Nevermore Academy.",
    relevanceScore: 88,
    matchReason: "A highly stylish dark comedy, ideal for high convenience and bite-sized viewing.",
    netflixUrl: "https://www.netflix.com/search?q=Wednesday",
    isOriginal: true
  },
  {
    id: "seed-10",
    title: "Kathal: A Jackfruit Mystery",
    year: "2023",
    genre: ["Comedy", "Social Satire"],
    languages: ["Hindi"],
    duration: "115m",
    description: "When two prized jackfruits disappear from a politician's garden, a young female inspector launches a bizarre interrogation to crack this high-profile case.",
    relevanceScore: 87,
    matchReason: "Sweet, light social satire and easy-going village humor.",
    netflixUrl: "https://www.netflix.com/search?q=Kathal",
    isOriginal: true
  },
  {
    id: "seed-11",
    title: "Red Notice",
    year: "2021",
    genre: ["Action", "Comedy", "Adventure"],
    languages: ["English", "Hindi"],
    duration: "117m",
    description: "An FBI profiler pursuing the world's most wanted art thief is forced to team up with a rival conman to execute a heist and capture an elusive master of heist.",
    relevanceScore: 85,
    matchReason: "Low effort, packed with popcorn action and charisma. Ideal for relaxing after work.",
    netflixUrl: "https://www.netflix.com/search?q=Red%20Notice",
    isOriginal: true
  },
  {
    id: "seed-12",
    title: "The Elephant Whisperers",
    year: "2022",
    genre: ["Documentary", "Nature"],
    languages: ["English", "Hindi"],
    duration: "41m",
    description: "In South India, a devoted indigenous couple form an incredibly deep, loving bond with an orphaned baby elephant named Raghu, creating an adorable, Oscar-winning family portrait.",
    relevanceScore: 97,
    matchReason: "Perfect fit when you have under 60 minutes. Deeply moving, gorgeous landscapes.",
    netflixUrl: "https://www.netflix.com/search?q=The%20Elephant%20Whisperers",
    isOriginal: true
  },
  {
    id: "seed-13",
    title: "Leave the World Behind",
    year: "2023",
    genre: ["Thriller", "Sci-Fi", "Apocalypse"],
    languages: ["English", "Hindi"],
    duration: "141m",
    description: "A luxury family vacation is interrupted when two strangers arrive at night, warning of an administrative blackout. As the tech collapses, both families must survive the mysterious apocalypse.",
    relevanceScore: 91,
    matchReason: "Provides an eerie, mysterious atmosphere perfect for an engaging weekend watch.",
    netflixUrl: "https://www.netflix.com/search?q=Leave%20the%20World%20Behind",
    isOriginal: true
  },
  {
    id: "seed-14",
    title: "Ludo",
    year: "2020",
    genre: ["Comedy", "Anthology", "Crime", "Drama"],
    languages: ["Hindi"],
    duration: "150m",
    description: "From a compromised tape to a suitcase filled with money, four wildly diverse stories overlap and collide under the whimsical hands of fate, luck, and an eccentric mastermind.",
    relevanceScore: 90,
    matchReason: "Colorful, chaotic, multi-threaded dark comedy with musical genius.",
    netflixUrl: "https://www.netflix.com/search?q=Ludo",
    isOriginal: true
  },
  {
    id: "seed-15",
    title: "Glass Onion: A Knives Out Mystery",
    year: "2022",
    genre: ["Comedy", "Mystery", "Whodunnit"],
    languages: ["English", "Hindi"],
    duration: "139m",
    description: "World-class detective Benoit Blanc travels to a private Greek island owned by a tech billionaire to unravel a luxury murder mystery game that turns fully real.",
    relevanceScore: 92,
    matchReason: "Smart, funny, high-gloss puzzle structure that will keep your entire family guessing.",
    netflixUrl: "https://www.netflix.com/search?q=Glass%20Onion",
    isOriginal: true
  }
];
